### ISSUE TITLE
Event Loop is still running

### ISSUE THREAD

**Issue by etkirsch** [etkirsch/pyna-colada#37]
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/etkirsch/Projects/pyna-colada/pyna/networking/RelayInterface.py", line 47, in serve_forever
    asyncio.get_event_loop().run_until_complete(self.receive())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/home/etkirsch/Projects/pyna-colada/pyna/networking/RelayInterface.py", line 68, in receive
    self.connect_to_relay()
  File "/home/etkirsch/Projects/pyna-colada/pyna/networking/RelayInterface.py", line 29, in connect_to_relay
    self.relay = asyncio.get_event_loop().run_until_complete(self.get_mesh_relay(self.relay_address, self.uid))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 304, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 271, in run_forever
    raise RuntimeError('Event loop is running.')
RuntimeError: Event loop is running.
```

**Comment by etkirsch** [comment]
May be resolved. Testing today.
